### ISSUE TITLE
add "how to run this app on your device" section on readme

### ISSUE THREAD

**Issue by thelittlemitak** [GeorgeHarland/RandomTower#1]
Hi George! I would love to do my first PR and start contributing to open source, which I never did before, and I thought for something simple like modifying the README with some installation tips (npm install for the dependencies etc.). If you allow me to work on that I would be more than grateful. I will also keep track of the game features but I would like to start very simple to understand the basics. Cheers mate! Jose

**Comment by GeorgeHarland** [comment]
Hey, absolutely you can. This is just a little side-project so any features you think would benefit the game, feel free to suggest!
Feel free to make a PR for the readme
And thanks for the interest!
- George

**Comment by GeorgeHarland** [comment]
Closed thanks to @thelittlemitak
